### ISSUE TITLE
JuliaError: Exception 'The solver `GLPK` or `GLPKMathProgInterface` cannot be set using `changeCobraSolver()'.

### ISSUE THREAD

**Issue by freiburgermsu** [opencobra/COBRA.jl#100]
Hello!

I receive the attached error 
![solver_setting_error](https://user-images.githubusercontent.com/60083977/172769234-61d1be1e-397f-4026-bdc9-70f1374d2385.JPG)
that the solver cannot be set through the `changeCobraSolver` function, despite that is what is demonstrated in [the docs](https://opencobra.github.io/COBRA.jl/stable/tutorials.html#Define-and-change-the-COBRA-solver-1). The corresponding files are all stored in [this directory](https://github.com/freiburgermsu/ProjectNotebooks/tree/main/CommunityModeling/julia). This error seems to occur in Windows OS and not in Linux.

How can the error be resolved?

Thank you :)
   Andrew

**Comment by mtefagh** [comment]
Hi Andrew,
The problem you mentioned should be solved after merging PR #110. Please let us know if this issue persists.
Best,
Mojtaba
