### ISSUE TITLE
add option to suppress messages

### ISSUE THREAD

**Issue by cossio** [opencobra/COBRA.jl#16]
`distributedFBA` prints some informative messages:

![image](https://user-images.githubusercontent.com/10637482/33941626-30ac4112-e00b-11e7-8d82-76a944665f75.png)

It would be nice if we were able to disable these messages. Sometimes you want to run FBA inside a script and parse the output for other purposes. These messages are then in the way.

**Comment by laurentheirendt** [comment]
@cossio, great suggestion! 👍 

Do you want to implement it? I can assist you if you need help. 🎉

**Comment by cossio** [comment]
sure, perhaps you can point me to the relevant code?

**Comment by laurentheirendt** [comment]
Great to hear that! 🎉 

The idea would be to implement a `printLevel` option in `distributedFBA`. For muting completely, `printLevel = 0`, while various levels of `printLevel` would print out more information to the command line. The relevant lines of code are in [`src/distributedFBA.jl`](https://github.com/opencobra/COBRA.jl/blob/master/src/distributedFBA.jl#L432), namely in the function `distributedFBA()`.

Are you familiar with `git` commands? May you submit a PR (pull request) to merge into the `develop` branch? We would also need to test this new functionality.

Looking forward to your contribution! 👍
