### ISSUE TITLE
COBRA cannot be used in v0.7

### ISSUE THREAD

**Issue by tkosaka1976** [opencobra/COBRA.jl#24]
I'm using COBRA.jl in julia v0.7.0 on macos 10.13.6.
These are error messages:

julia> using COBRA
[ Info: Precompiling COBRA [58298e0b-d05c-52ec-a210-0694647ebfc7]
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/COBRA.jl:19.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/COBRA.jl:19
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/checkSetup.jl:32.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/checkSetup.jl:32
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/checkSetup.jl:68.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/checkSetup.jl:68
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:25.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/load.jl:25
┌ Warning: Deprecated syntax `type` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:25.
│ Use `mutable struct` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/load.jl:25
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:77.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/load.jl:77
WARNING: importing deprecated binding Base.SparseMatrixCSC into COBRA.
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:9
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:9
WARNING: Base.SparseMatrixCSC is deprecated, run `using SparseArrays` to load sparse array functionality
  likely near /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/load.jl:9
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:19.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:19
┌ Warning: Deprecated syntax `type` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:19.
│ Use `mutable struct` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:19
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:49.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:49
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:94.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:94
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:188.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:188
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/solve.jl:236.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/solve.jl:236
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:48.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:48
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:160.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:160
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:332.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:332
┌ Warning: Deprecated syntax `multiple line breaks between doc string and object` at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:507.
│ Use `at most one line break` instead.
└ @ ~/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:507
ERROR: LoadError: LoadError: syntax: invalid escape sequence
Stacktrace:
 [1] include at ./boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at ./loading.jl:1038
 [3] include at ./sysimg.jl:29 [inlined]
 [4] include(::String) at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/COBRA.jl:19
 [5] top-level scope at none:0
 [6] include at ./boot.jl:317 [inlined]
 [7] include_relative(::Module, ::String) at ./loading.jl:1038
 [8] include(::Module, ::String) at ./sysimg.jl:29
 [9] top-level scope at none:2
 [10] eval at ./boot.jl:319 [inlined]
 [11] eval(::Expr) at ./client.jl:399
 [12] top-level scope at ./none:3
in expression starting at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/distributedFBA.jl:608
in expression starting at /Users/kousaka_tomoyuki/.julia/packages/COBRA/nAHE8/src/COBRA.jl:30
ERROR: Failed to precompile COBRA [58298e0b-d05c-52ec-a210-0694647ebfc7] to /Users/kousaka_tomoyuki/.julia/compiled/v0.7/COBRA/ChOhi.ji.
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] macro expansion at ./logging.jl:313 [inlined]
 [3] compilecache(::Base.PkgId, ::String) at ./loading.jl:1185
 [4] macro expansion at ./logging.jl:311 [inlined]
 [5] _require(::Base.PkgId) at ./loading.jl:941
 [6] require(::Base.PkgId) at ./loading.jl:852
 [7] macro expansion at ./logging.jl:311 [inlined]
 [8] require(::Module, ::Symbol) at ./loading.jl:834

**Comment by laurentheirendt** [comment]
Thanks for reporting this, @tkosaka1976. We are well aware of that, and we are working on making COBRA.jl compatible with the latest versions of Julia as soon as its dependencies are. For instance, [MAT.jl](https://github.com/JuliaIO/MAT.jl) or [WinRPM](https://github.com/JuliaPackaging/WinRPM.jl) are not yet compatible, which hinders the COBRA.jl package of being compatible.

For now, may you use Julia 0.6.4? Thanks.

**Comment by tkosaka1976** [comment]
I can use 0.6.4.
If I need, I'll downgrade and use it.
Thank you for your effort and inform.

**Comment by laurentheirendt** [comment]
Thanks for your understanding @tkosaka1976 👍  Maybe [this post](https://discourse.julialang.org/t/jump-and-julia-0-7-1-0/12964) on discourse is also of interest.
