### ISSUE TITLE
Support Julia 1.0

### ISSUE THREAD

**Issue by cossio** [opencobra/COBRA.jl#38]

**Comment by 14ndy15** [comment]
MAT.jl is now compatible with Julia 1.0 (https://github.com/JuliaIO/MAT.jl/releases/tag/v0.5.0)

**Comment by pagnani** [comment]
We developed a package for analysing metabolic networks
[https://github.com/anna-pa-m/Metabolic-EP](url)

which currently depends on COBRA. 

As the blocking issue on MAT.jl seems to be solved, do you have a timeline for updating COBRA to 1.0?

Just to organise our work. 

Thanks a lot for porting COBRA to julia!

**Comment by laurentheirendt** [comment]
Great to hear that!

Yes, COBRA.jl will be made compatible with Julia 1.0 soon - probably just in time for the next JuliaCon.

**Comment by leejm516** [comment]
With a few changes, I found the current source code nicely worked in Julia 1.1, although all the functions and the solvers have not been tested yet. Does this issue still need someone to contribute?

**Comment by laurentheirendt** [comment]
@leejm516, ayn contributions are welcome. Feel free to open a PR. Thanks.

**Comment by laurentheirendt** [comment]
https://github.com/opencobra/COBRA.jl/pull/46

**Comment by cossio** [comment]
@laurentheirendt Why close this?

**Comment by laurentheirendt** [comment]
@cossio, because the transition is almost done. See #46

**Comment by cossio** [comment]
@laurentheirendt Great work!
